name: Static analysis

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/static_analysis.yml'
      - 'src/**'
      - 'pylintrc'
      - 'setup.cfg'
  pull_request:
    branches:
      - master

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --deploy --system

    - name: PyLint
      run: make pylint

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --deploy --system

    - name: Flake8
      run: make flake8

  typing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --deploy --system

    - name: MyPy typing check
      run: make mypy

