# This workflow will install Python dependencies and run tests.

name: Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'src/**'
      - 'tests/**'
      - 'Pipfile.lock'
      # Even if we change the packaging, we should test it as we are
      # testing against installation and not the source codes only 
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'tox.ini'
  pull_request:
    branches:
      - master

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      env:
        # Disable the spinner as it massively pollutes the output
        TOX_PARALLEL_NO_SPINNER: 1
      # Running tests in parallel with `-p` option
      run: |
        tox -p
    - name: Upload test results
      uses: actions/upload-artifact@v2
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      with:
        name: test-results-${{ matrix.python-version }}-${{ matrix.os }}
        path: test_results/*.xml

  publish-test-results:
    name: "Publish tests results"
    needs: [tests]
    runs-on: ubuntu-latest
    # The `tests` job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: "Test results"
          comment_title: "Test results"
          files: artifacts/**/*_tests.xml
